In [1]:
import sys
import spotipy 
import spotipy.util as util
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#uthorizations for Spotify API
scope = "user-library-read"
if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    print("Usage: %s username" % (sys.argv[0],))
    sys.exit()
token = util.prompt_for_user_token(username,scope,client_id="e80ff3306b0f43f7b115893e02093168",
                                   client_secret="bd5644e705be458c81d1175f037f9eb3",redirect_uri="http://localhost/")

In [3]:
sp=spotipy.Spotify(auth=token)
sp1=sp.search(q="year:2019",type = "track",limit=10,market="us")
song = []
album = []
pop=[]
artist=[]
for i,t in enumerate (sp1["tracks"]["items"]):
    name_1=(i,t["name"])
    album_1=(t["album"]["name"])
    song.append(name_1[1])
    album.append(album_1)
    pop.append(t["popularity"])
    artist.append(t["artists"][0]["name"])
final = {
    "Name": song,
    "Album":album,
    "Popularity":pop,
    "Artist":artist
}

df = pd.DataFrame(final)
new_df=df.sort_values(["Popularity"],ascending=False)

new_df

,Name,Album,Popularity,Artist
8,Memories,Memories,100,Maroon 5
0,Circles,Hollywood's Bleeding,99,Post Malone
1,HIGHEST IN THE ROOM,HIGHEST IN THE ROOM,98,Travis Scott
4,everything i wanted,everything i wanted,98,Billie Eilish
5,Lose You To Love Me,Lose You To Love Me,98,Selena Gomez
2,ROXANNE,ROXANNE,97,Arizona Zervas
6,hot girl bummer,hot girl bummer,96,blackbear
3,Bandit (with YoungBoy Never Broke Again),Bandit (with YoungBoy Never Broke Again),93,Juice WRLD
7,BOP,KIRK,91,DaBaby
9,223's (feat. 9lokknine),223's (feat. 9lokknine),90,YNW Melly

In [4]:
playlist_name = []
p_id = []
owners_p=[]

playlists=sp.search(q="Top 50",type = "playlist",limit=50)
for x,y in enumerate(playlists["playlists"]["items"]):
    play_name = (x,y["name"])
    playlist_id = y["uri"]
    owners = (y["owner"]["display_name"])
    #owner_final=owners[]
    if owners == "spotifycharts":
        playlist_name.append(play_name[1])
        p_id.append(playlist_id)
        owners_p.append(owners)

play_final = {
    "Playlist Name":playlist_name,
    "Playlist_ID":p_id,
    "Owners":owners_p
}
playlist_df = pd.DataFrame(play_final)
playlist_df

,Playlist Name,Playlist_ID,Owners
0,Global Top 50,spotify:playlist:37i9dQZEVXbMDoHDwVN2tF,spotifycharts
1,Brazil Top 50,spotify:playlist:37i9dQZEVXbMXbN3EUUhlg,spotifycharts
2,Spain Top 50,spotify:playlist:37i9dQZEVXbNFJfN1Vw8d9,spotifycharts
3,Germany Top 50,spotify:playlist:37i9dQZEVXbJiZcmkrIHGU,spotifycharts
4,Mexico Top 50,spotify:playlist:37i9dQZEVXbO3qyFxbkOE1,spotifycharts
5,Netherlands Top 50,spotify:playlist:37i9dQZEVXbKCF6dqVpDkS,spotifycharts
6,Argentina Top 50,spotify:playlist:37i9dQZEVXbMMy2roB9myp,spotifycharts
7,Australia Top 50,spotify:playlist:37i9dQZEVXbJPcfkRz0wJ0,spotifycharts
8,Italy Top 50,spotify:playlist:37i9dQZEVXbIQnj7RRhdSX,spotifycharts
9,Japan Top 50,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,spotifycharts
10,Sweden Top 50,spotify:playlist:37i9dQZEVXbLoATJ81JYXz,spotifycharts
11,Chile Top 50,spotify:playlist:37i9dQZEVXbL0GavIqMTeb,spotifycharts
12,Indonesia Top 50,spotify:playlist:37i9dQZEVXbObFQZ3JLcXt,spotifycharts
13,France Top 50,spotify:playlist:37i9dQZEVXbIPWwFssbupI,spotifycharts
14,Philippines Top 50,spotify:playlist:37i9dQZEVXbNBz9cRCSFkY,spotifycharts
15,Norway Top 50,spotify:playlist:37i9dQZEVXbJvfa0Yxg7E7,spotifycharts
16,India Top 50,spotify:playlist:37i9dQZEVXbLZ52XmnySJg,spotifycharts
17,Colombia Top 50,spotify:playlist:37i9dQZEVXbOa2lmxNORXQ,spotifycharts
18,Turkey Top 50,spotify:playlist:37i9dQZEVXbIVYVBNw9D5K,spotifycharts
19,United States Top 50,spotify:playlist:37i9dQZEVXbLRQDuF5jeBp,spotifycharts
20,Peru Top 50,spotify:playlist:37i9dQZEVXbJfdy5b0KP7W,spotifycharts
21,United Kingdom Top 50,spotify:playlist:37i9dQZEVXbLnolsZ8PSNw,spotifycharts
22,Finland Top 50,spotify:playlist:37i9dQZEVXbMxcczTSoGwZ,spotifycharts
23,Ireland Top 50,spotify:playlist:37i9dQZEVXbKM896FDX8L1,spotifycharts
24,Denmark Top 50,spotify:playlist:37i9dQZEVXbL3J0k32lWnN,spotifycharts
25,Paraguay Top 50,spotify:playlist:37i9dQZEVXbNOUPGj7tW6T,spotifycharts
26,Canada Top 50,spotify:playlist:37i9dQZEVXbKj23U1GF4IR,spotifycharts
27,Taiwan Top 50,spotify:playlist:37i9dQZEVXbMnZEatlMSiu,spotifycharts
28,Poland Top 50,spotify:playlist:37i9dQZEVXbN6itCcaL3Tt,spotifycharts
29,Belgium Top 50,spotify:playlist:37i9dQZEVXbJNSeeHswcKB,spotifycharts
30,Thailand Top 50,spotify:playlist:37i9dQZEVXbMnz8KIWsvf9,spotifycharts
31,Singapore Top 50,spotify:playlist:37i9dQZEVXbK4gjvS1FjPY,spotifycharts
32,Malaysia Top 50,spotify:playlist:37i9dQZEVXbJlfUljuZExa,spotifycharts
33,Ecuador Top 50,spotify:playlist:37i9dQZEVXbJlM6nvL1nD1,spotifycharts
34,Portugal Top 50,spotify:playlist:37i9dQZEVXbKyJS56d1pgi,spotifycharts
35,Panama Top 50,spotify:playlist:37i9dQZEVXbKypXHVwk1f0,spotifycharts
36,Uruguay Top 50,spotify:playlist:37i9dQZEVXbMJJi3wgRbAy,spotifycharts
37,Guatemala Top 50,spotify:playlist:37i9dQZEVXbLy5tBFyQvd4,spotifycharts
38,Hungary Top 50,spotify:playlist:37i9dQZEVXbNHwMxAkvmF8,spotifycharts
39,Bolivia Top 50,spotify:playlist:37i9dQZEVXbJqfMFK4d691,spotifycharts
40,Vietnam Top 50,spotify:playlist:37i9dQZEVXbLdGSmz6xilI,spotifycharts

In [5]:
playlist_name_t = []
p_id_t = []
owners_p_t=[]

playlists=sp.search(q="Hong Kong Top 50",type = "playlist",limit=50)
for x,y in enumerate(playlists["playlists"]["items"]):
    play_name = (x,y["name"])
    playlist_id = y["uri"]
    owners = (y["owner"]["display_name"])
    #owner_final=owners[]
    if owners == "spotifycharts":
        playlist_name_t.append(play_name[1])
        p_id_t.append(playlist_id)
        owners_p_t.append(owners)

play_final_t = {
    "Playlist Name":playlist_name_t,
    "Playlist_ID":p_id_t,
    "Owners":owners_p_t
}
playlist_df_t = pd.DataFrame(play_final_t)
playlist_df_t.tail()

        Playlist Name                              Playlist_ID         Owners
0    Hong Kong Top 50  spotify:playlist:37i9dQZEVXbLwpL8TjsxOG  spotifycharts
1  Hong Kong Viral 50  spotify:playlist:37i9dQZEVXbKXd6qahcpCg  spotifycharts

In [6]:
final_playists_df = pd.concat([playlist_df,playlist_df_t])
final_playists_df

,Playlist Name,Playlist_ID,Owners
0,Global Top 50,spotify:playlist:37i9dQZEVXbMDoHDwVN2tF,spotifycharts
1,Brazil Top 50,spotify:playlist:37i9dQZEVXbMXbN3EUUhlg,spotifycharts
2,Spain Top 50,spotify:playlist:37i9dQZEVXbNFJfN1Vw8d9,spotifycharts
3,Germany Top 50,spotify:playlist:37i9dQZEVXbJiZcmkrIHGU,spotifycharts
4,Mexico Top 50,spotify:playlist:37i9dQZEVXbO3qyFxbkOE1,spotifycharts
5,Netherlands Top 50,spotify:playlist:37i9dQZEVXbKCF6dqVpDkS,spotifycharts
6,Argentina Top 50,spotify:playlist:37i9dQZEVXbMMy2roB9myp,spotifycharts
7,Australia Top 50,spotify:playlist:37i9dQZEVXbJPcfkRz0wJ0,spotifycharts
8,Italy Top 50,spotify:playlist:37i9dQZEVXbIQnj7RRhdSX,spotifycharts
9,Japan Top 50,spotify:playlist:37i9dQZEVXbKXQ4mDTEBXq,spotifycharts
10,Sweden Top 50,spotify:playlist:37i9dQZEVXbLoATJ81JYXz,spotifycharts
11,Chile Top 50,spotify:playlist:37i9dQZEVXbL0GavIqMTeb,spotifycharts
12,Indonesia Top 50,spotify:playlist:37i9dQZEVXbObFQZ3JLcXt,spotifycharts
13,France Top 50,spotify:playlist:37i9dQZEVXbIPWwFssbupI,spotifycharts
14,Philippines Top 50,spotify:playlist:37i9dQZEVXbNBz9cRCSFkY,spotifycharts
15,Norway Top 50,spotify:playlist:37i9dQZEVXbJvfa0Yxg7E7,spotifycharts
16,India Top 50,spotify:playlist:37i9dQZEVXbLZ52XmnySJg,spotifycharts
17,Colombia Top 50,spotify:playlist:37i9dQZEVXbOa2lmxNORXQ,spotifycharts
18,Turkey Top 50,spotify:playlist:37i9dQZEVXbIVYVBNw9D5K,spotifycharts
19,United States Top 50,spotify:playlist:37i9dQZEVXbLRQDuF5jeBp,spotifycharts
20,Peru Top 50,spotify:playlist:37i9dQZEVXbJfdy5b0KP7W,spotifycharts
21,United Kingdom Top 50,spotify:playlist:37i9dQZEVXbLnolsZ8PSNw,spotifycharts
22,Finland Top 50,spotify:playlist:37i9dQZEVXbMxcczTSoGwZ,spotifycharts
23,Ireland Top 50,spotify:playlist:37i9dQZEVXbKM896FDX8L1,spotifycharts
24,Denmark Top 50,spotify:playlist:37i9dQZEVXbL3J0k32lWnN,spotifycharts
25,Paraguay Top 50,spotify:playlist:37i9dQZEVXbNOUPGj7tW6T,spotifycharts
26,Canada Top 50,spotify:playlist:37i9dQZEVXbKj23U1GF4IR,spotifycharts
27,Taiwan Top 50,spotify:playlist:37i9dQZEVXbMnZEatlMSiu,spotifycharts
28,Poland Top 50,spotify:playlist:37i9dQZEVXbN6itCcaL3Tt,spotifycharts
29,Belgium Top 50,spotify:playlist:37i9dQZEVXbJNSeeHswcKB,spotifycharts
30,Thailand Top 50,spotify:playlist:37i9dQZEVXbMnz8KIWsvf9,spotifycharts
31,Singapore Top 50,spotify:playlist:37i9dQZEVXbK4gjvS1FjPY,spotifycharts
32,Malaysia Top 50,spotify:playlist:37i9dQZEVXbJlfUljuZExa,spotifycharts
33,Ecuador Top 50,spotify:playlist:37i9dQZEVXbJlM6nvL1nD1,spotifycharts
34,Portugal Top 50,spotify:playlist:37i9dQZEVXbKyJS56d1pgi,spotifycharts
35,Panama Top 50,spotify:playlist:37i9dQZEVXbKypXHVwk1f0,spotifycharts
36,Uruguay Top 50,spotify:playlist:37i9dQZEVXbMJJi3wgRbAy,spotifycharts
37,Guatemala Top 50,spotify:playlist:37i9dQZEVXbLy5tBFyQvd4,spotifycharts
38,Hungary Top 50,spotify:playlist:37i9dQZEVXbNHwMxAkvmF8,spotifycharts
39,Bolivia Top 50,spotify:playlist:37i9dQZEVXbJqfMFK4d691,spotifycharts
40,Vietnam Top 50,spotify:playlist:37i9dQZEVXbLdGSmz6xilI,spotifycharts
0,Hong Kong Top 50,spotify:playlist:37i9dQZEVXbLwpL8TjsxOG,spotifycharts
1,Hong Kong Viral 50,spotify:playlist:37i9dQZEVXbKXd6qahcpCg,spotifycharts

In [10]:
import requests
tracks = []
p_id2=[]
test = []
p_name = []
t_ids = []
tracker=[]
p_list=final_playists_df["Playlist_ID"]
data=p_list.str.split(":")
for x in data:
    id =(x[2])
    p_id2.append(id)
# headers = {"Content-Type":"application/json",
#     "Authorization":"Bearer BQCIClJ0R1Nax6u2XKpRBCupS4kVHZmeaRYuIrnb47moSjBvbZkUrQxkKR62JCdfqIRGk1i4w_8C34zn4agYbL-M9dPtaa-PHFQqujADBrxfSQPLtJIhdu6ZAkjBUiaTP3cgTU-ucPw "}
for x in p_id2:
    response_json=sp.user_playlist_tracks("spotifycharts", x)
    response_json["items"]
    rank=1
    cur_play = final_playists_df.loc[final_playists_df["Playlist_ID"] == f"spotify:playlist:{x}"]["Playlist Name"].unique()[0]
    counter = 0
    for i,t in enumerate (response_json["items"]):
        name=(t["track"]["name"])
        t_id=(t["track"]["id"])
        tracks.append(name)
        t_ids.append(t_id)
        test.append(x)
        p_name.append(cur_play)
        rank = rank + 1
        tracker.append(counter+1)
        counter+=1
        if (rank == 6):
            break

In [11]:
music_df = pd.DataFrame({
    "Playlist Name" : p_name,
    "Playlist ID" : test,
    "Song" : tracks,
    "ID":t_ids,
    "Rank":tracker
})
music_df["Playlist Name"] = music_df["Playlist Name"].replace({'United States Top 50' : 'US Top 50', 'United Kingdom Top 50' : 'UK Top 50', 'Hong Kong Viral 50': 'HK Viral 50'})
music_df
#music_df.to_csv("data.csv")

,Playlist Name,Playlist ID,Song,ID,Rank
0,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,1
1,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,2
2,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,ROXANNE,696DnlkuDOXcMAnKlTgXXK,3
3,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Circles,21jGcNKet2qwijlDFuPiPb,4
4,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Memories,2b8fOow8UzyDFAE27YhOZM,5
...,...,...,...,...,...
210,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Lost in the Woods,7namdlOhbtsc8FvoSafOQt,1
211,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Falling,4TnjEaWOeW0eKTKIEvJyCa,2
212,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Into the Unknown,3Z0oQ8r78OUaHvGPiDBR3W,3
213,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,All Is Found,61HVbcNeRACZpyvHrc3AnD,4
214,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Bauhinia Rhapsody,6gTAS57L0jTyk4OrenilJS,5

In [12]:
country = []
Range=music_df["Playlist Name"].str.split(" ")[:,]
#Range=music_df["Playlist Name"].str.split("Top 50")

for x in Range:
    n_c=(x[0])
    country.append(n_c)
music_df["Country"]=country
music_df
music_df.to_csv("music.csv")

music_df

,Playlist Name,Playlist ID,Song,ID,Rank,Country
0,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,1,Global
1,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,2,Global
2,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,ROXANNE,696DnlkuDOXcMAnKlTgXXK,3,Global
3,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Circles,21jGcNKet2qwijlDFuPiPb,4,Global
4,Global Top 50,37i9dQZEVXbMDoHDwVN2tF,Memories,2b8fOow8UzyDFAE27YhOZM,5,Global
...,...,...,...,...,...,...
210,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Lost in the Woods,7namdlOhbtsc8FvoSafOQt,1,HK
211,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Falling,4TnjEaWOeW0eKTKIEvJyCa,2,HK
212,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Into the Unknown,3Z0oQ8r78OUaHvGPiDBR3W,3,HK
213,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,All Is Found,61HVbcNeRACZpyvHrc3AnD,4,HK
214,HK Viral 50,37i9dQZEVXbKXd6qahcpCg,Bauhinia Rhapsody,6gTAS57L0jTyk4OrenilJS,5,HK

In [13]:
m_country=["Hong","Netherlands","Russia","Australia","Canada","France","Japan","Germany","US", "UK"]
final_music_1=music_df.loc[music_df["Country"].isin(m_country)]
final_music=final_music_1.reset_index()
final_music.to_csv("../Resources/Final.csv")
final_music

,index,Playlist Name,Playlist ID,Song,ID,Rank,Country
0,15,Germany Top 50,37i9dQZEVXbJiZcmkrIHGU,KEIN SCHLAF,6416zJN0FGPmh1Ph4BH2h3,1,Germany
1,16,Germany Top 50,37i9dQZEVXbJiZcmkrIHGU,COLT,76IVpz47q3ghkxoUeTTEKb,2,Germany
2,17,Germany Top 50,37i9dQZEVXbJiZcmkrIHGU,Roller,6hw1Sy9wZ8UCxYGdpKrU6M,3,Germany
3,18,Germany Top 50,37i9dQZEVXbJiZcmkrIHGU,Der Bratan bleibt der gleiche,2M39v73rNJmAXUXIW0oagP,4,Germany
4,19,Germany Top 50,37i9dQZEVXbJiZcmkrIHGU,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,5,Germany
5,25,Netherlands Top 50,37i9dQZEVXbKCF6dqVpDkS,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,1,Netherlands
6,26,Netherlands Top 50,37i9dQZEVXbKCF6dqVpDkS,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,2,Netherlands
7,27,Netherlands Top 50,37i9dQZEVXbKCF6dqVpDkS,Pa Olvidarte,1RO8Q3w2Jkir8cvvGEApI0,3,Netherlands
8,28,Netherlands Top 50,37i9dQZEVXbKCF6dqVpDkS,ROXANNE,696DnlkuDOXcMAnKlTgXXK,4,Netherlands
9,29,Netherlands Top 50,37i9dQZEVXbKCF6dqVpDkS,Memories,2b8fOow8UzyDFAE27YhOZM,5,Netherlands
10,35,Australia Top 50,37i9dQZEVXbJPcfkRz0wJ0,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,1,Australia
11,36,Australia Top 50,37i9dQZEVXbJPcfkRz0wJ0,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,2,Australia
12,37,Australia Top 50,37i9dQZEVXbJPcfkRz0wJ0,ROXANNE,696DnlkuDOXcMAnKlTgXXK,3,Australia
13,38,Australia Top 50,37i9dQZEVXbJPcfkRz0wJ0,Circles,21jGcNKet2qwijlDFuPiPb,4,Australia
14,39,Australia Top 50,37i9dQZEVXbJPcfkRz0wJ0,Don't Start Now,6WrI0LAC5M1Rw2MnX2ZvEg,5,Australia
15,45,Japan Top 50,37i9dQZEVXbKXQ4mDTEBXq,Pretender,58dxGXavrcagRqA58fNB0Z,1,Japan
16,46,Japan Top 50,37i9dQZEVXbKXQ4mDTEBXq,Hakujitsu,0mNO3xUzjsI17GXO1DRFCH,2,Japan
17,47,Japan Top 50,37i9dQZEVXbKXQ4mDTEBXq,宿命,2yozZfRYHP7Elsymghu5t3,3,Japan
18,48,Japan Top 50,37i9dQZEVXbKXQ4mDTEBXq,イエスタデイ,3S3DDZrPOYTirleXRyHnNM,4,Japan
19,49,Japan Top 50,37i9dQZEVXbKXQ4mDTEBXq,ノーダウト,5DMEvbg3gUmiR5HIBWdveV,5,Japan
20,65,France Top 50,37i9dQZEVXbIPWwFssbupI,Ne reviens pas,4TnFANpjVwVKWzkxNzIyFH,1,France
21,66,France Top 50,37i9dQZEVXbIPWwFssbupI,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,2,France
22,67,France Top 50,37i9dQZEVXbIPWwFssbupI,Popopop,18HNGxDOcshRU2Hdu8tMOM,3,France
23,68,France Top 50,37i9dQZEVXbIPWwFssbupI,Mayday (feat. Ninho),1SVuEeerYIwjCRsF5MGzX3,4,France
24,69,France Top 50,37i9dQZEVXbIPWwFssbupI,Jamais,2MCAs3ttHSuDm1RHL0rqTF,5,France
25,95,US Top 50,37i9dQZEVXbLRQDuF5jeBp,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,1,US
26,96,US Top 50,37i9dQZEVXbLRQDuF5jeBp,Bandit (with YoungBoy Never Broke Again),6Gg1gjgKi2AK4e0qzsR7sd,2,US
27,97,US Top 50,37i9dQZEVXbLRQDuF5jeBp,Robbery,6Hj9jySrnFppAI0sEMCZpJ,3,US
28,98,US Top 50,37i9dQZEVXbLRQDuF5jeBp,Legends,1Knctxx9vGZxpZfF66BIEa,4,US
29,99,US Top 50,37i9dQZEVXbLRQDuF5jeBp,All Girls Are The Same,4VXIryQMWpIdGgYR4TrjT1,5,US
30,105,UK Top 50,37i9dQZEVXbLnolsZ8PSNw,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,1,UK
31,106,UK Top 50,37i9dQZEVXbLnolsZ8PSNw,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,2,UK
32,107,UK Top 50,37i9dQZEVXbLnolsZ8PSNw,All I Want for Christmas Is You,0bYg9bo50gSsH3LtXe2SQn,3,UK
33,108,UK Top 50,37i9dQZEVXbLnolsZ8PSNw,Own It (feat. Ed Sheeran & Burna Boy),07s9NNOT0sZQp7TyolLLgu,4,UK
34,109,UK Top 50,37i9dQZEVXbLnolsZ8PSNw,Last Christmas,2FRnf9qhLbvw8fu4IBXx78,5,UK
35,130,Canada Top 50,37i9dQZEVXbKj23U1GF4IR,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,1,Canada
36,131,Canada Top 50,37i9dQZEVXbKj23U1GF4IR,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,2,Canada
37,132,Canada Top 50,37i9dQZEVXbKj23U1GF4IR,Bandit (with YoungBoy Never Broke Again),6Gg1gjgKi2AK4e0qzsR7sd,3,Canada
38,133,Canada Top 50,37i9dQZEVXbKj23U1GF4IR,ROXANNE,696DnlkuDOXcMAnKlTgXXK,4,Canada
39,134,Canada Top 50,37i9dQZEVXbKj23U1GF4IR,Robbery,6Hj9jySrnFppAI0sEMCZpJ,5,Canada
40,205,Hong Kong Top 50,37i9dQZEVXbLwpL8TjsxOG,Señorita,6v3KW9xbzN5yKLt9YKDYA2,1,Hong
41,206,Hong Kong Top 50,37i9dQZEVXbLwpL8TjsxOG,Memories,2b8fOow8UzyDFAE27YhOZM,2,Hong
42,207,Hong Kong Top 50,37i9dQZEVXbLwpL8TjsxOG,Circles,21jGcNKet2qwijlDFuPiPb,3,Hong
43,208,Hong Kong Top 50,37i9dQZEVXbLwpL8TjsxOG,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,4,Hong
44,209,Hong Kong Top 50,37i9dQZEVXbLwpL8TjsxOG,everything i wanted,3ZCTVFBt2Brf31RLEnCkWJ,5,Hong

In [98]:
#url="https://api.spotify.com/v1/audio-features/{id}"
headers = {"Content-Type":"application/json",
    "Authorization":"Bearer BQAs053_JHSB3Qk0vbC1J5stWRYgIx4_V9QXeNpGoVaymZ58XiJOvSUp2QIeJgoqTk8fr1MhpSaQctLgEVY1w_1jfacvhOKPGmKCghY98px8pumPXWlgAhumwHUiinmW5IMHv2S4riU"}

track_response=requests.get("https://api.spotify.com/v1/audio-features/696DnlkuDOXcMAnKlTgXXK",headers=headers).json()
track_response

{'danceability': 0.621,
 'energy': 0.601,
 'key': 6,
 'loudness': -5.616,
 'mode': 0,
 'speechiness': 0.148,
 'acousticness': 0.0522,
 'instrumentalness': 0,
 'liveness': 0.46,
 'valence': 0.457,
 'tempo': 116.735,
 'type': 'audio_features',
 'id': '696DnlkuDOXcMAnKlTgXXK',
 'uri': 'spotify:track:696DnlkuDOXcMAnKlTgXXK',
 'track_href': 'https://api.spotify.com/v1/tracks/696DnlkuDOXcMAnKlTgXXK',
 'analysis_url': 'https://api.spotify.com/v1/audio-analysis/696DnlkuDOXcMAnKlTgXXK',
 'duration_ms': 163636,
 'time_signature': 5}

In [14]:
track_ids = final_music["ID"]
def t_analysis (track_ids):
    headers = {"Content-Type":"application/json",
    "Authorization":"Bearer BQAs053_JHSB3Qk0vbC1J5stWRYgIx4_V9QXeNpGoVaymZ58XiJOvSUp2QIeJgoqTk8fr1MhpSaQctLgEVY1w_1jfacvhOKPGmKCghY98px8pumPXWlgAhumwHUiinmW5IMHv2S4riU"}
    
    danceability = []
    energy = []
    loudness = []
    speechiness = []
    acousticness = []
    instrumentalness = []
    liveness = []
    valence = []
    tempo = []
    tr_id = []
    for x in track_ids:
        url= f"https://api.spotify.com/v1/audio-features/{x}"
        t_r=requests.get(url,headers=headers).json()
        danceability.append(t_r.get('danceability', 0))
        energy.append(t_r.get('energy', 0))
        loudness.append(t_r.get('loudness', 0))
        speechiness.append(t_r.get('speechiness', 0))
        acousticness.append(t_r.get('acousticness', 0))
        instrumentalness.append(t_r.get('instrumentalness', 0))
        liveness.append(t_r.get('liveness', 0))
        valence.append(t_r.get('valence', 0))
        tempo.append(t_r.get('tempo', 0))
        tr_id.append(t_r.get('id', 0))
    return danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,tr_id

In [15]:
a,b,c,d,e,f,g,h,i,j=t_analysis(track_ids)

In [17]:
dict_1 = {
    "Danceability": a,
    "Energy":b,
    "Loudness":c,
    "Speechiness":d,
    "acousticness":e,
    "instrumentalness":f,
    "liveness":g,
    "valence":h,
    "tempo":i,
     "ID": j,
}
fin_1=pd.DataFrame(dict_1)
#fin_1.to_csv("newtest.csv")
fin_1

,Danceability,Energy,Loudness,Speechiness,acousticness,instrumentalness,liveness,valence,tempo,ID
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0

In [16]:
#merge table with Playlist Table
df_merged = fin_1.merge(final_music, how='outer', left_index=True, right_index=True)
df_merged.head(10)

NameError: name 'fin_1' is not defined

In [135]:
new_df = df_merged.groupby(["Country"])
mean_value=new_df.mean()
final_mean_value = mean_value.reset_index()
final_mean_value

,Country,Danceability,Energy,Loudness,Speechiness,acousticness,instrumentalness,liveness,valence,tempo,index,Rank
0,Australia,0.7398,0.6138,-5.4488,0.08502,0.356340,0.000520,0.17874,0.5604,109.9630,32,6
1,Canada,0.6014,0.6662,-5.7614,0.08718,0.220504,0.000535,0.18082,0.4188,131.0172,132,6
2,France,0.8072,0.6420,-5.8248,0.19532,0.324220,0.000134,0.15470,0.5344,122.0420,67,6
3,Germany,0.7056,0.6600,-5.7588,0.24836,0.295720,0.000585,0.23082,0.4944,117.2510,17,6
4,Hong,0.7494,0.4896,-7.5220,0.06426,0.531640,0.131920,0.10546,0.5320,109.2224,212,6
5,Japan,0.5612,0.8166,-3.7950,0.05586,0.166980,0.000000,0.25440,0.5928,125.7816,52,6
6,Netherlands,0.6526,0.5998,-6.8406,0.09100,0.479840,0.000032,0.19400,0.5664,109.2158,27,6
7,UK,0.5646,0.4764,-9.3596,0.05088,0.512600,0.000034,0.28836,0.6188,103.6016,107,6
8,US,0.5716,0.7018,-5.2162,0.07708,0.087644,0.000505,0.16722,0.4246,131.2112,97,6

In [1]:

x_axis = np.arange(len(final_mean_value))
tick_locations = [value for value in x_axis]
fig,ax=plt.subplots(figsize=(50,20))

bar_1=plt.bar(x_axis+0.10, final_mean_value["Danceability"], label="Danceability", color='r', width=0.10)
bar_2=plt.bar(x_axis+0.20, final_mean_value["Energy"],label="Energy", color='g', width=0.10)
bar_3=plt.bar(x_axis+0.30, final_mean_value["Speechiness"], label="Speechiness",color='b', width=0.10)
bar_4=plt.bar(x_axis+0.40, final_mean_value["acousticness"], label="acousticness", color='y', width=0.10)
bar_5=plt.bar(x_axis+0.50, final_mean_value["instrumentalness"], label="instrumentalness",color='purple', width=0.10)
bar_6=plt.bar(x_axis+0.60, final_mean_value["liveness"],label="liveness", color='c', width=0.10)
bar_7=plt.bar(x_axis+0.70, final_mean_value["valence"],label="valence",  color='darkorange', width=0.10)
#plt.bar(x_axis+0.80, final_mean_value["tempo"], color='tan', width=0.10)
#plt.bar(x_axis+0.20, final_mean_value["Loudness"], color='deeppink', width=0.10)

#x_labels = ["Australia","Danceability","Energy","Speechiness","acousticness","instrumentalness"
       #   "liveness","valence"]

#plt.setp(ax,xticks=[0,1,2,3,4,5,6,7,8,9],xticklabels = x_labels)
plt.legend()
plt.grid()

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()/2,.5*height,"%d" %int(height)+ "%",ha="center",va="bottom",color="white")
autolabel(bar_1)
autolabel(bar_2)
autolabel(bar_3)
autolabel(bar_4)
autolabel(bar_5)
autolabel(bar_6)
autolabel(bar_7)

plt.xticks(tick_locations, final_mean_value["Country"], rotation="vertical")
plt.savefig("avg_feature_country.png")

NameError: name 'np' is not defined